import type { ProjectConfig } from './types'

export function createDefaultProject(): ProjectConfig {
  return {
    budgetCredits: 100_000,
    terrain: {
      gridSize: 72,
      worldSizeM: 240,
      baseSoil: 'misto',
      meanMoisturePct: 42,
      nutrients: { n: 55, p: 38, k: 46 },
      ph: 6.4,
      meanTempC: 12,
      seasonalTempAmpC: 10,
      altitudeMinM: 120,
      altitudeMaxM: 260,
      roughness: 0.55,
      shadePatchiness: 0.35,
    },
    climate: {
      meanRainMmDay: 3.2,
      windMean: 0.35,
      droughtChancePerDay: 0.012,
      stormChancePerDay: 0.006,
      wildfireChancePerDay: 0.0015,
      diseaseChancePerDay: 0.002,
    },
    species: [
      {
        id: 'quercus_robur',
        name: 'Quercus robur (rovere)',
        form: 'latifoglia',
        maxHeightM: 32,
        maxTrunkRadiusM: 0.55,
        maxCanopyRadiusM: 7.5,
        rootDepthM: 3.2,
        waterUsePerDay: 0.55,
        nutrientUsePerDay: { n: 0.5, p: 0.35, k: 0.45 },
        seed: { distanceM: 26, probabilityPerDay: 0.02, minMoisturePct: 28, phMin: 5.2, phMax: 7.6 },
        tolerance: { tempMinC: -12, tempMaxC: 36, drought: 0.45, phMin: 4.8, phMax: 8.0 },
        germinationDays: 21,
        maturityDays: 3650,
        shadePreference: 0.35,
        color: { canopy: '#2e8b57', trunk: '#5b4636' },
      },
      {
        id: 'pinus_sylvestris',
        name: 'Pinus sylvestris (pino silvestre)',
        form: 'conifera',
        maxHeightM: 28,
        maxTrunkRadiusM: 0.42,
        maxCanopyRadiusM: 5.2,
        rootDepthM: 2.4,
        waterUsePerDay: 0.38,
        nutrientUsePerDay: { n: 0.32, p: 0.22, k: 0.25 },
        seed: { distanceM: 34, probabilityPerDay: 0.03, minMoisturePct: 18, phMin: 4.6, phMax: 7.2 },
        tolerance: { tempMinC: -20, tempMaxC: 35, drought: 0.7, phMin: 4.2, phMax: 7.6 },
        germinationDays: 18,
        maturityDays: 2550,
        shadePreference: 0.18,
        color: { canopy: '#2b6b4b', trunk: '#4c3a2e' },
      },
      {
        id: 'corylus_avellana',
        name: 'Corylus avellana (nocciolo)',
        form: 'arbusto',
        maxHeightM: 6,
        maxTrunkRadiusM: 0.12,
        maxCanopyRadiusM: 2.2,
        rootDepthM: 1.0,
        waterUsePerDay: 0.45,
        nutrientUsePerDay: { n: 0.28, p: 0.2, k: 0.22 },
        seed: { distanceM: 16, probabilityPerDay: 0.04, minMoisturePct: 30, phMin: 5.4, phMax: 7.8 },
        tolerance: { tempMinC: -15, tempMaxC: 34, drought: 0.55, phMin: 5.0, phMax: 8.2 },
        germinationDays: 14,
        maturityDays: 900,
        shadePreference: 0.7,
        color: { canopy: '#2f7d4a', trunk: '#5a4b3d' },
      },
      {
        id: 'rubus_fruticosus',
        name: 'Rubus fruticosus (rovo)',
        form: 'arbusto',
        maxHeightM: 2,
        maxTrunkRadiusM: 0.03,
        maxCanopyRadiusM: 0.9,
        rootDepthM: 0.5,
        waterUsePerDay: 0.52,
        nutrientUsePerDay: { n: 0.18, p: 0.1, k: 0.14 },
        seed: { distanceM: 10, probabilityPerDay: 0.07, minMoisturePct: 24, phMin: 5.0, phMax: 7.8 },
        tolerance: { tempMinC: -18, tempMaxC: 38, drought: 0.6, phMin: 4.6, phMax: 8.2 },
        germinationDays: 9,
        maturityDays: 260,
        shadePreference: 0.55,
        color: { canopy: '#3b8f55', trunk: '#3c2f28' },
      },
    ],
  }
}
